### ISSUE TITLE
agent.mysql plugin: replication.last_io_error metric not captured

### ISSUE THREAD

**Issue by inflatador** [virgo-agent-toolkit/rackspace-monitoring-agent#955]
Hello agent devs,

Per https://developer.rackspace.com/docs/rackspace-monitoring/v1/tech-ref-info/check-type-reference/#agent-mysql , agent.mysql captures a metric called "replication.last_io_error," which contains "The error message of the most recent error that caused the I/O thread to stop."

I've been looking into putting this metric into alarms such as 

 _if (metric['replication.slave_sql_running'] != "Yes") {

  return new AlarmStatus(CRITICAL, 'Replica SQL thread is not running with error number  #{replication.last_errno} and error #{replication.last_io_error} ');

}
return new AlarmStatus(OK, 'Replication slave_sql_running is OK');_ 

so we can have more informative emails or tickets upon replication failure.

Unfortunately, it doesn't look like this metric is being collected by the agent, as it doesn't show up as an available metric in Intelligence or the Metrics API. I've tested this with Cloud Databases and with the monitoring agent 2.6.10 directly on a cloud server, and neither appear to be working.

**Comment by harageth** [comment]
This metric was being gathered. The issue was that the last_errno is displaying an error number for the last error and not the last_io_error, which in this particular case was null in the database. We have updated the agent with both last_error and last_io_errno and should be releasing a new agent update today or tomorrow.

I believe this should resolve this issue so I will close this.

**Comment by rphillips** [comment]
2.6.13 has been released.
